Repository danivijay/react-commerce, pull requests merged in 2019-03, with the labels that each got.

#2 feat: init readme
  README.md
Labels: enhancement

#4 fix(readme): add guideline link, add more info in contribution section
  README.md
Labels: bug, enhancement

#5 feat: init added router to home page
  package-lock.json
  package.json
  src/App.jsx
  src/App.scss
  src/Home.jsx
Labels: enhancement

#9 feat: add contributing.md
  CONTRIBUTING.md
Labels: feature

#10 feat: link contribution guide
  README.md
Labels: feature

#11 feat(contributing): add project wiki link
  CONTRIBUTING.md
Labels: feature

#12 feat(pwa): mod manifest, icons, favicon, change titles
  public/favicon.ico
  public/images/icons/icon-128x128.png
  public/images/icons/icon-144x144.png
  public/images/icons/icon-152x152.png
  public/images/icons/icon-192x192.png
  public/images/icons/icon-384x384.png
  public/images/icons/icon-512x512.png
  public/images/icons/icon-72x72.png
  public/images/icons/icon-96x96.png
  public/index.html
  public/manifest.json
Labels: feature

#14 fix: contribution guide stylefix
  README.md
Labels: feature

#15 feat(contribution): add steps, optimize existing content
  CONTRIBUTING.md
Labels: feature

#16 feat: Header and Footer
  src/App.jsx
  src/App.scss
  src/Cards.jsx
  src/Cards.scss
  src/Cart.jsx
  src/Footer.jsx
  src/Footer.scss
  src/Home.jsx
  src/Navbar.jsx
  src/Navbar.scss
Labels: feature

#17 feat: convert to black and white
  src/App.scss
  src/Cards.jsx
  src/Cards.scss
  src/Footer.jsx
  src/Footer.scss
  src/Navbar.scss
Labels: ui

#20 feat: Home-page-layout & restructuring of project
  package-lock.json
  src/App.jsx
  src/Cart.jsx
  src/Components/Common/Cards.jsx
  src/Components/Common/Cards.scss
  src/Components/Common/Filterbar.jsx
  src/Components/Common/Footer.jsx
  src/Components/Common/Footer.scss
  src/Components/Common/Hero.jsx
  src/Components/Common/Hero.scss
  src/Components/Common/Navbar.jsx
  src/Components/Common/Navbar.scss
  src/Components/Pages/Cart.jsx
  src/Components/Pages/Home.jsx
  src/Home.jsx
  src/Navbar.jsx
Labels: refactor, ui
